### PR TITLE
Allow dynamic dates based on a pattern

### PR DESCRIPTION
**Pull request by Tzeentchful**
The Issue

The current way to display time on a hologram is very limited.

Justification for this PR:

Allow more more customization of holograms, providing a more "all in one" package. 

PR Breakdown

Adds a new tag that can be specified on hologram creation.
The tag is: %date:'date format'%
The 'date format' part will be phrased by java's SimpleDateFormat then the whole tag is replaced by the output.
The syntax can be found here: http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html

 eg: The time is: %date:"h:mm a"% will be The time is: 12:08 PM

Relevant PR(s) and Issue(s)

Currently it's pointless to display any unit below minutes.
Since holograms are only refreshed every 1 minute.

### CODE REVIEW

**Comment by DSH105** [comment]
Please follow the [PR guidelines for formatting](https://github.com/DSH105/HoloAPI/blob/master/CONTRIBUTING.md#pull-request-formatting).

We want to make sure that all PRs to the API are nicely formatted and clear to read, so it's important to start maintaining that standard now :).

**Comment by Tzeentchful** [comment]
Done

**Comment by stuntguy3000** [comment]
I would like to point out, remove the TABS and turn them info four spaces. Example/related: #30 

Notice how with yours, each line has been modified? Whereas with mine only the new lines have been added.

**Comment by stuntguy3000** [comment]
There we go :)

**Comment by Tzeentchful** [comment]
My formater is set to tab by default since i find it easier to handle.

**Pull request merged**
