### PR TITLE
More precise positioning of holograms

### PR DESCRIPTION
**Pull request by Tzeentchful**
Changed the hologram generation to take doubles instead of integers.
This allows holograms to be placed with more precise positions.

### CODE REVIEW

**Comment by DSH105** [comment]
This doesn't really make much of a difference, as the spawning packet only takes integers.

**Comment by Tzeentchful** [comment]
It is sent as an integer yes. But the integer is a fixed point number so a greater precision can be achieved by the minecraft client. 
"X position as a Fixed-Point number"
...
http://wiki.vg/Protocol#Spawn_Mob
http://wiki.vg/Data_Types#Fixed-point_numbers

**Comment by DSH105** [comment]
Ah, I see. Awesome, thanks ;D

**Comment by hawkfalcon** [comment]
Works http://www.hawkfalcon.com/screenshots/0228212416.png :D

**Comment by DSH105** [comment]
;D

**Comment by Tzeentchful** [comment]
\o/

**Pull request merged**
