### PR TITLE
Add basic events, begin framework for event expansion

### PR DESCRIPTION
**Pull request by stuntguy3000**
**The Issue**
Holo_API_ is lacking just that (sort-of) and deserves an Event system.

**Justification for this PR:**
This is an API, the place where an Event system belongs.

Currently, HoloCreateEvent has not been implemented due to my lack of knowledge of how this bundle of joy works. I plan to add/expand on the event system soon.

### CODE REVIEW

**Comment by drtshock** [comment]
Why change from HologramCreateEvent to HoloCreateEvent?

**Comment by drtshock** [comment]
Thanks! I patched this up a bit before I merged it. https://github.com/DSH105/HoloAPI/compare/aaa41eec4444...c3cab876ef3a

**Comment by stuntguy3000** [comment]
"Why change from HologramCreateEvent to HoloCreateEvent?" To add a "standard" naming 'space' for the events.

**Comment by drtshock** [comment]
I changed them all to have 'Holo'EventSomething :)

**Pull request closed without merging**
