### PR TITLE
Added tagConversion API

### PR DESCRIPTION
**Pull request by ghost**
This is a simple method for the Devs can add their Tags

Example:

TagConversion.addConverion("test", 
                    new TagFunctor() {

```
            @Override
            public String getValue(Player pl) {
                return "Funciona";
            }
        });
```

"Estado: %test%" ---->  "Estado: Funciona"

### CODE REVIEW

**Comment by CaptainBern** [comment]
While the idea is very interesting, I have my doubts about your implementation, and therefor this will not get pulled. Here are a few reasons why:
- You didn't document your PR properly, please do so. (see: [Contributing Guidelines](https://github.com/DSH105/HoloAPI/wiki/Contributing) for more info)
- Your code doesn't follow all of our coding-standards. (see above)
- The name, "TagFunctor", why that name? I have no idea what your toughts are when you hear the word "Functor" but the first thing that comes in my mind is the mathematical term. Try searching for a better name. Something like "TagProvider" or so, since it "provides" a tag. 
- Your implementation lacks a compatibility system across multiple "tags". Example: 2 plugins register a tag, they both need it. How are you going to solve this? At the moment the plugin that registers it's tag last get's it but this is ofcourse something we need to avoid. All plugins should be able to register a custom tag. Maybe hop by on IRC and then we can discuss this.

Once you've made the requested chance I will pull.
Thank you
- Cap.

**Comment by khmMinecraftProjects** [comment]
Thank for your response, and sorry for not document the request, I didn't read this document. 

The request is only the idea. My code is very simple, It haven't the essentials options and It isn't secure. I prefer that You implements this because You know better the plugin.

I usually use the class Functor for do It beacause this's a class that receive parameters and depends the class(Functor) returns one or other value. The name of the class isn't important, you can rename as you like.

Finally, apology my english, I try to explain in the best way possible

**Comment by CaptainBern** [comment]
No problem. We'll look into this. 
Thank you for your contribution.

**Comment by lol768** [comment]
Have you considered leaving the PR open so he can change these things?

**Comment by CaptainBern** [comment]
You're right, execuse me. I won't re-open it though since he already stated that this is more an "idea".

**Comment by DSH105** [comment]
I like this idea. Thanks for the pull request @khmDEV :)

**Pull request closed without merging**
